/*
file generated by qcc, do not modify
Ported from QW/server/progdefs.h (GNU GPL v2 or later; QW's copy carries the
same "file generated by qcc" banner as WinQuake's progdefs.q1/progdefs.h and
no separate license text of its own).

This is QuakeWorld's `globalvars_t`/`entvars_t` pair, laid out fresh from
QW/server/progdefs.h -- a different qcc build than WinQuake's progdefs.q1, so
its word offsets differ. Diffed field-by-field against src/progs/progdefs.ts
(WinQuake, PROGHEADER_CRC 5927):

- `globalvars_t`: QW adds one field, `int newmis` (right after `frametime`,
  before `force_retouch`), and drops three, `deathmatch`/`coop`/`teamplay`
  (WinQuake had them between `mapname` and `serverflags`; in QW those three
  are cvars instead -- server.h `extern cvar_t teamplay, deathmatch;`, no
  `coop` cvar at all). Net: WinQuake's 92 global words become QW's 90.
- `entvars_t`: QW adds one field, `float lastruntime` (right after `ltime`,
  before `movetype`), and drops two, `punchangle` (vec3_t, between
  `avelocity` and `classname` in WinQuake) and `idealpitch` (float, between
  `fixangle`/`v_angle` and `netname` in WinQuake). Net: WinQuake's 105 entity
  field words become QW's 102.

Both PROGHEADER_CRC (54730 here vs 5927 for WinQuake) and every other
offset shift downstream of these adds/drops confirm the two structs are
qcc outputs of genuinely different QuakeC source, not a copy-paste with
one field renamed -- exactly what QW's separate `QW/progs` source tree
implies. PROGHEADER_CRC 54730 is checked against
`../qsrc/quake/QW/progs/qwprogs.dat`'s header word in this unit's test.

The offset tables and the `QwGlobalVars`/`QwEntVars` accessor classes are
generated from src/progs/progdefs_layout.ts's union field tables by the same
generator src/progs/progdefs.ts uses for WinQuake's layout; the ordered name
lists below are the whole of QuakeWorld's difference. See that module's
header for the technique and for the union-accessor deviation (reaching for
`deathmatch`/`coop`/`teamplay`/`punchangle`/`idealpitch` on a QuakeWorld
layout throws, naming the field).
*/

import {
  ENTVARS_FIELDS,
  GLOBALVARS_FIELDS,
  ProgsVarsT,
  buildProgsLayout,
  installVarAccessors,
  layoutOffsets,
  type EntVarFieldsT,
  type GlobalVarFieldsT,
} from "../../progs/progdefs_layout";

export const PROGHEADER_CRC = 54730;

const QW_GLOBAL_NAMES = [
  "self",
  "other",
  "world",
  "time",
  "frametime",
  "newmis",
  "force_retouch",
  "mapname",
  "serverflags",
  "total_secrets",
  "total_monsters",
  "found_secrets",
  "killed_monsters",
  "parm1",
  "parm2",
  "parm3",
  "parm4",
  "parm5",
  "parm6",
  "parm7",
  "parm8",
  "parm9",
  "parm10",
  "parm11",
  "parm12",
  "parm13",
  "parm14",
  "parm15",
  "parm16",
  "v_forward",
  "v_up",
  "v_right",
  "trace_allsolid",
  "trace_startsolid",
  "trace_fraction",
  "trace_endpos",
  "trace_plane_normal",
  "trace_plane_dist",
  "trace_ent",
  "trace_inopen",
  "trace_inwater",
  "msg_entity",
  "main",
  "StartFrame",
  "PlayerPreThink",
  "PlayerPostThink",
  "ClientKill",
  "ClientConnect",
  "PutClientInServer",
  "ClientDisconnect",
  "SetNewParms",
  "SetChangeParms",
] as const;

export const QW_GLOBALS_LAYOUT = buildProgsLayout(28, GLOBALVARS_FIELDS, QW_GLOBAL_NAMES);

export const QW_GLOBAL_OFS = layoutOffsets(QW_GLOBALS_LAYOUT, QW_GLOBAL_NAMES);

export const QW_NUM_GLOBAL_WORDS = QW_GLOBALS_LAYOUT.words;

export interface QwGlobalVars extends GlobalVarFieldsT {}
export class QwGlobalVars extends ProgsVarsT {
  constructor(f: Float32Array, i: Int32Array) {
    super(f, i, QW_GLOBALS_LAYOUT);
  }
}
installVarAccessors(QwGlobalVars.prototype, QW_GLOBALS_LAYOUT, GLOBALVARS_FIELDS);

const QW_ENTVARS_NAMES = [
  "modelindex",
  "absmin",
  "absmax",
  "ltime",
  "lastruntime",
  "movetype",
  "solid",
  "origin",
  "oldorigin",
  "velocity",
  "angles",
  "avelocity",
  "classname",
  "model",
  "frame",
  "skin",
  "effects",
  "mins",
  "maxs",
  "size",
  "touch",
  "use",
  "think",
  "blocked",
  "nextthink",
  "groundentity",
  "health",
  "frags",
  "weapon",
  "weaponmodel",
  "weaponframe",
  "currentammo",
  "ammo_shells",
  "ammo_nails",
  "ammo_rockets",
  "ammo_cells",
  "items",
  "takedamage",
  "chain",
  "deadflag",
  "view_ofs",
  "button0",
  "button1",
  "button2",
  "impulse",
  "fixangle",
  "v_angle",
  "netname",
  "enemy",
  "flags",
  "colormap",
  "team",
  "max_health",
  "teleport_time",
  "armortype",
  "armorvalue",
  "waterlevel",
  "watertype",
  "ideal_yaw",
  "yaw_speed",
  "aiment",
  "goalentity",
  "spawnflags",
  "target",
  "targetname",
  "dmg_take",
  "dmg_save",
  "dmg_inflictor",
  "owner",
  "movedir",
  "message",
  "sounds",
  "noise",
  "noise1",
  "noise2",
  "noise3",
] as const;

export const QW_ENTVARS_LAYOUT = buildProgsLayout(0, ENTVARS_FIELDS, QW_ENTVARS_NAMES);

export const QW_ENTVARS_OFS = layoutOffsets(QW_ENTVARS_LAYOUT, QW_ENTVARS_NAMES);

export const QW_ENTVARS_SIZE_WORDS = QW_ENTVARS_LAYOUT.words;

export interface QwEntVars extends EntVarFieldsT {}
export class QwEntVars extends ProgsVarsT {
  constructor(f: Float32Array, i: Int32Array) {
    super(f, i, QW_ENTVARS_LAYOUT);
  }
}
installVarAccessors(QwEntVars.prototype, QW_ENTVARS_LAYOUT, ENTVARS_FIELDS);
