/*
Copyright (C) 1996-1997 Id Software, Inc.
Ported from WinQuake/progdefs.q1 and QW/server/progdefs.h (GNU GPL v2 or
later; both carry qcc's "file generated by qcc, do not modify" banner).

The two qcc-generated `globalvars_t`/`entvars_t` layouts the engine can run
(WinQuake's, PROGHEADER_CRC 5927, and QuakeWorld's, 54730) differ only in
which fields are present and therefore in every offset downstream of the
first difference. This module is the one place the *shape* of those structs
is declared, so one accessor generator serves both hosts:

- `GLOBALVARS_FIELDS` / `ENTVARS_FIELDS` are the union of every field either
  layout declares, each with its storage kind (`float` and `vector` read the
  Float32Array view, `int` -- string_t, func_t, entity and the C's plain
  `int` fields -- reads the Int32Array view). The union order is WinQuake's,
  with QuakeWorld's two additions (`newmis`, `lastruntime`) inserted at the
  position QW's own progdefs.h puts them.
- `GlobalVarFieldsT` / `EntVarFieldsT` -- and through them the whole accessor
  types `ProgsGlobalVarsT` / `ProgsEntVarsT` -- are *derived* from those two
  lists by a mapped type, so the accessor types and the field tables can never
  desync.
- A concrete layout (`buildProgsLayout`) is that union filtered to one host's
  ordered name list, with the word offsets computed by walking the list from
  the struct's base (28 for globalvars_t's `pad[28]`, 0 for entvars_t).
  `layoutOffsets` hands back the same offset table typed by the caller's own
  name tuple, so `GLOBAL_OFS.self` keeps the exact literal-key typing the
  hand-written tables had.
- `installVarAccessors` writes the getters/setters onto an accessor class's
  prototype: float/int fields read and write their word through the shared
  view pair, vector fields return the persistent `subarray` view the
  constructor built (so `VectorCopy(ent.v.origin, out)` still costs no
  allocation and the view is a `Vec3` directly).

Deviations from the C source:
- `globalvars_t` and `entvars_t` are two C structs with disjoint field sets
  per host; here one accessor *type* covers the union, because progs.ts's
  `pr` state holder is shared by both hosts and TypeScript cannot give one
  object two field sets. A field the *active* layout does not declare
  (`deathmatch` under QuakeWorld, `newmis` under WinQuake) gets a throwing
  accessor naming the field, so reaching for the wrong host's global fails
  loudly instead of reading a word that isn't there. The C could not make
  this mistake because it compiled one struct per binary; this port catches
  it at the first access instead.
- The accessors live on the class prototype rather than being generated per
  instance: an edict's field block is allocated once per edict (up to
  MAX_EDICTS of them at map load), so per-instance `defineProperty` calls
  would cost thousands of property installations per level.
*/

import type { Vec3 } from "../common/mathlib";
import { SysError } from "../platform/sys";

export type FieldKindT = "float" | "int" | "vector";

export interface LayoutFieldT {
  readonly name: string;
  readonly kind: FieldKindT;
}

// globalvars_t, WinQuake's field order with QW's `newmis` in QW's position.
// WinQuake-only: deathmatch, coop, teamplay. QuakeWorld-only: newmis.
export const GLOBALVARS_FIELDS = [
  { name: "self", kind: "int" },
  { name: "other", kind: "int" },
  { name: "world", kind: "int" },
  { name: "time", kind: "float" },
  { name: "frametime", kind: "float" },
  { name: "newmis", kind: "int" },
  { name: "force_retouch", kind: "float" },
  { name: "mapname", kind: "int" },
  { name: "deathmatch", kind: "float" },
  { name: "coop", kind: "float" },
  { name: "teamplay", kind: "float" },
  { name: "serverflags", kind: "float" },
  { name: "total_secrets", kind: "float" },
  { name: "total_monsters", kind: "float" },
  { name: "found_secrets", kind: "float" },
  { name: "killed_monsters", kind: "float" },
  { name: "parm1", kind: "float" },
  { name: "parm2", kind: "float" },
  { name: "parm3", kind: "float" },
  { name: "parm4", kind: "float" },
  { name: "parm5", kind: "float" },
  { name: "parm6", kind: "float" },
  { name: "parm7", kind: "float" },
  { name: "parm8", kind: "float" },
  { name: "parm9", kind: "float" },
  { name: "parm10", kind: "float" },
  { name: "parm11", kind: "float" },
  { name: "parm12", kind: "float" },
  { name: "parm13", kind: "float" },
  { name: "parm14", kind: "float" },
  { name: "parm15", kind: "float" },
  { name: "parm16", kind: "float" },
  { name: "v_forward", kind: "vector" },
  { name: "v_up", kind: "vector" },
  { name: "v_right", kind: "vector" },
  { name: "trace_allsolid", kind: "float" },
  { name: "trace_startsolid", kind: "float" },
  { name: "trace_fraction", kind: "float" },
  { name: "trace_endpos", kind: "vector" },
  { name: "trace_plane_normal", kind: "vector" },
  { name: "trace_plane_dist", kind: "float" },
  { name: "trace_ent", kind: "int" },
  { name: "trace_inopen", kind: "float" },
  { name: "trace_inwater", kind: "float" },
  { name: "msg_entity", kind: "int" },
  { name: "main", kind: "int" },
  { name: "StartFrame", kind: "int" },
  { name: "PlayerPreThink", kind: "int" },
  { name: "PlayerPostThink", kind: "int" },
  { name: "ClientKill", kind: "int" },
  { name: "ClientConnect", kind: "int" },
  { name: "PutClientInServer", kind: "int" },
  { name: "ClientDisconnect", kind: "int" },
  { name: "SetNewParms", kind: "int" },
  { name: "SetChangeParms", kind: "int" },
] as const;

// entvars_t, WinQuake's field order with QW's `lastruntime` in QW's position.
// WinQuake-only: punchangle, idealpitch. QuakeWorld-only: lastruntime.
export const ENTVARS_FIELDS = [
  { name: "modelindex", kind: "float" },
  { name: "absmin", kind: "vector" },
  { name: "absmax", kind: "vector" },
  { name: "ltime", kind: "float" },
  { name: "lastruntime", kind: "float" },
  { name: "movetype", kind: "float" },
  { name: "solid", kind: "float" },
  { name: "origin", kind: "vector" },
  { name: "oldorigin", kind: "vector" },
  { name: "velocity", kind: "vector" },
  { name: "angles", kind: "vector" },
  { name: "avelocity", kind: "vector" },
  { name: "punchangle", kind: "vector" },
  { name: "classname", kind: "int" },
  { name: "model", kind: "int" },
  { name: "frame", kind: "float" },
  { name: "skin", kind: "float" },
  { name: "effects", kind: "float" },
  { name: "mins", kind: "vector" },
  { name: "maxs", kind: "vector" },
  { name: "size", kind: "vector" },
  { name: "touch", kind: "int" },
  { name: "use", kind: "int" },
  { name: "think", kind: "int" },
  { name: "blocked", kind: "int" },
  { name: "nextthink", kind: "float" },
  { name: "groundentity", kind: "int" },
  { name: "health", kind: "float" },
  { name: "frags", kind: "float" },
  { name: "weapon", kind: "float" },
  { name: "weaponmodel", kind: "int" },
  { name: "weaponframe", kind: "float" },
  { name: "currentammo", kind: "float" },
  { name: "ammo_shells", kind: "float" },
  { name: "ammo_nails", kind: "float" },
  { name: "ammo_rockets", kind: "float" },
  { name: "ammo_cells", kind: "float" },
  { name: "items", kind: "float" },
  { name: "takedamage", kind: "float" },
  { name: "chain", kind: "int" },
  { name: "deadflag", kind: "float" },
  { name: "view_ofs", kind: "vector" },
  { name: "button0", kind: "float" },
  { name: "button1", kind: "float" },
  { name: "button2", kind: "float" },
  { name: "impulse", kind: "float" },
  { name: "fixangle", kind: "float" },
  { name: "v_angle", kind: "vector" },
  { name: "idealpitch", kind: "float" },
  { name: "netname", kind: "int" },
  { name: "enemy", kind: "int" },
  { name: "flags", kind: "float" },
  { name: "colormap", kind: "float" },
  { name: "team", kind: "float" },
  { name: "max_health", kind: "float" },
  { name: "teleport_time", kind: "float" },
  { name: "armortype", kind: "float" },
  { name: "armorvalue", kind: "float" },
  { name: "waterlevel", kind: "float" },
  { name: "watertype", kind: "float" },
  { name: "ideal_yaw", kind: "float" },
  { name: "yaw_speed", kind: "float" },
  { name: "aiment", kind: "int" },
  { name: "goalentity", kind: "int" },
  { name: "spawnflags", kind: "float" },
  { name: "target", kind: "int" },
  { name: "targetname", kind: "int" },
  { name: "dmg_take", kind: "float" },
  { name: "dmg_save", kind: "float" },
  { name: "dmg_inflictor", kind: "int" },
  { name: "owner", kind: "int" },
  { name: "movedir", kind: "vector" },
  { name: "message", kind: "int" },
  { name: "sounds", kind: "float" },
  { name: "noise", kind: "int" },
  { name: "noise1", kind: "int" },
  { name: "noise2", kind: "int" },
  { name: "noise3", kind: "int" },
] as const;

type ScalarsOf<F extends readonly LayoutFieldT[]> = {
  -readonly [E in Extract<F[number], { kind: "float" | "int" }> as E["name"]]: number;
};

type VectorsOf<F extends readonly LayoutFieldT[]> = {
  readonly [E in Extract<F[number], { kind: "vector" }> as E["name"]]: Vec3;
};

// The field sets themselves, derived from the tables above so the accessor
// types and the tables can never desync.
export interface GlobalVarFieldsT extends ScalarsOf<typeof GLOBALVARS_FIELDS>, VectorsOf<typeof GLOBALVARS_FIELDS> {}

export interface EntVarFieldsT extends ScalarsOf<typeof ENTVARS_FIELDS>, VectorsOf<typeof ENTVARS_FIELDS> {}

export interface ProgsLayoutT {
  readonly fields: readonly LayoutFieldT[];
  readonly offsets: Readonly<Record<string, number>>;
  readonly words: number; // the struct's total size, in 4-byte words
}

// pr_edict.c's `type_size[]` for the three storage kinds this table uses:
// string_t, func_t, entity and void* are all one 32-bit word.
const KIND_WORDS: Readonly<Record<FieldKindT, number>> = { float: 1, int: 1, vector: 3 };

export function buildProgsLayout(base: number, all: readonly LayoutFieldT[], names: readonly string[]): ProgsLayoutT {
  const byName = new Map<string, LayoutFieldT>();
  for (const field of all) byName.set(field.name, field);

  const offsets: Record<string, number> = {};
  const fields: LayoutFieldT[] = [];
  let words = base;
  for (const name of names) {
    const spec = byName.get(name);
    if (spec === undefined) throw new SysError(`buildProgsLayout: no such field "${name}"`);
    if (name in offsets) throw new SysError(`buildProgsLayout: duplicate field "${name}"`);
    offsets[name] = words;
    words += KIND_WORDS[spec.kind];
    fields.push(spec);
  }
  return { fields, offsets, words };
}

function hasEveryName<N extends string>(
  offsets: Readonly<Record<string, number>>,
  names: readonly N[],
): offsets is Readonly<Record<N, number>> {
  for (const name of names) if (!(name in offsets)) return false;
  return true;
}

// The layout's offset table, typed by the caller's own field-name tuple, so
// `GLOBAL_OFS.self` resolves to a number and `GLOBAL_OFS.nosuchfield` is a
// compile error, exactly as the hand-written `as const` tables were.
export function layoutOffsets<N extends string>(layout: ProgsLayoutT, names: readonly N[]): Readonly<Record<N, number>> {
  const offsets = layout.offsets;
  if (!hasEveryName(offsets, names)) throw new SysError("layoutOffsets: layout is missing a named field");
  return offsets;
}

// The accessor classes' shared base: it owns the view pair every generated
// getter reads through and the persistent vector views, but declares no
// fields of its own -- installVarAccessors puts those on the subclass
// prototype.
export class ProgsVarsT {
  readonly vec: Vec3[] = [];

  constructor(
    readonly f: Float32Array,
    readonly i: Int32Array,
    layout: ProgsLayoutT,
  ) {
    for (const field of layout.fields) {
      if (field.kind !== "vector") continue;
      const ofs = layout.offsets[field.name];
      this.vec.push(f.subarray(ofs, ofs + 3));
    }
  }
}

// A whole accessor object: the shared base plus one struct's fields. Either
// host's concrete class (GlobalVars/QwGlobalVars, EntVars/QwEntVars) satisfies
// the matching alias, which is what lets one `ProgsStateT` hold either.
export type ProgsGlobalVarsT = ProgsVarsT & GlobalVarFieldsT;

export type ProgsEntVarsT = ProgsVarsT & EntVarFieldsT;

export function installVarAccessors(proto: object, layout: ProgsLayoutT, all: readonly LayoutFieldT[]): void {
  let vecIndex = 0;
  const present = new Set<string>();

  for (const field of layout.fields) {
    present.add(field.name);
    const ofs = layout.offsets[field.name];
    if (field.kind === "vector") {
      const k = vecIndex++;
      Object.defineProperty(proto, field.name, {
        get(this: ProgsVarsT): Vec3 {
          return this.vec[k];
        },
      });
    } else if (field.kind === "float") {
      Object.defineProperty(proto, field.name, {
        get(this: ProgsVarsT): number {
          return this.f[ofs];
        },
        set(this: ProgsVarsT, value: number) {
          this.f[ofs] = value;
        },
      });
    } else {
      Object.defineProperty(proto, field.name, {
        get(this: ProgsVarsT): number {
          return this.i[ofs];
        },
        set(this: ProgsVarsT, value: number) {
          this.i[ofs] = value;
        },
      });
    }
  }

  // Fields the other host's progdefs declares and this one does not: see the
  // file header's union-accessor note.
  for (const field of all) {
    if (present.has(field.name)) continue;
    const absent = (): never => {
      throw new SysError(`progdefs: "${field.name}" is not a field of this progs layout`);
    };
    Object.defineProperty(proto, field.name, { get: absent, set: absent });
  }
}
