/*
file generated by qcc, do not modify
Ported from WinQuake/progdefs.q1 (the canonical, up-to-date copy of this
struct pair -- progdefs.h in the tree only `#include`s progdefs.q1 or
progdefs.q2 depending on the QUAKE2 define, plus its own GPL license header;
diffed byte-for-byte against progdefs.q1 and it carries no struct content of
its own, so there is nothing to reconcile).

`globalvars_t` and `entvars_t` are qcc-generated layouts: every global and
every entity field QuakeC declares is addressed by a fixed word offset into
one shared `Float32Array`/`Int32Array` pair (`pr_globals` for globals, an
edict's own field block for entvars). This is WinQuake's build of that pair
(PROGHEADER_CRC 5927); QuakeWorld's is src/qw/server/progdefs.ts. Both are
now ordered name lists filtered out of progdefs_layout.ts's union field
tables, and both get their offset tables and their accessor classes from
that module's one generator -- see its header for the technique and for the
one deviation the sharing introduces (a field the other host declares and
this one does not throws when reached, instead of being a compile error as
it was while the two hosts had separate hand-written accessor classes).
*/

import {
  ENTVARS_FIELDS,
  GLOBALVARS_FIELDS,
  ProgsVarsT,
  buildProgsLayout,
  installVarAccessors,
  layoutOffsets,
  type EntVarFieldsT,
  type GlobalVarFieldsT,
} from "./progdefs_layout";

export const PROGHEADER_CRC = 5927;

// globalvars_t's `int pad[28]` is the base; QuakeC's own globals follow the
// struct, so the last name below is the last *system* global, not the last
// global in the file.
const NQ_GLOBAL_NAMES = [
  "self",
  "other",
  "world",
  "time",
  "frametime",
  "force_retouch",
  "mapname",
  "deathmatch",
  "coop",
  "teamplay",
  "serverflags",
  "total_secrets",
  "total_monsters",
  "found_secrets",
  "killed_monsters",
  "parm1",
  "parm2",
  "parm3",
  "parm4",
  "parm5",
  "parm6",
  "parm7",
  "parm8",
  "parm9",
  "parm10",
  "parm11",
  "parm12",
  "parm13",
  "parm14",
  "parm15",
  "parm16",
  "v_forward",
  "v_up",
  "v_right",
  "trace_allsolid",
  "trace_startsolid",
  "trace_fraction",
  "trace_endpos",
  "trace_plane_normal",
  "trace_plane_dist",
  "trace_ent",
  "trace_inopen",
  "trace_inwater",
  "msg_entity",
  "main",
  "StartFrame",
  "PlayerPreThink",
  "PlayerPostThink",
  "ClientKill",
  "ClientConnect",
  "PutClientInServer",
  "ClientDisconnect",
  "SetNewParms",
  "SetChangeParms",
] as const;

export const NQ_GLOBALS_LAYOUT = buildProgsLayout(28, GLOBALVARS_FIELDS, NQ_GLOBAL_NAMES);

export const GLOBAL_OFS = layoutOffsets(NQ_GLOBALS_LAYOUT, NQ_GLOBAL_NAMES);

export const NUM_GLOBAL_WORDS = NQ_GLOBALS_LAYOUT.words;

export interface GlobalVars extends GlobalVarFieldsT {}
export class GlobalVars extends ProgsVarsT {
  constructor(f: Float32Array, i: Int32Array) {
    super(f, i, NQ_GLOBALS_LAYOUT);
  }
}
installVarAccessors(GlobalVars.prototype, NQ_GLOBALS_LAYOUT, GLOBALVARS_FIELDS);

const NQ_ENTVARS_NAMES = [
  "modelindex",
  "absmin",
  "absmax",
  "ltime",
  "movetype",
  "solid",
  "origin",
  "oldorigin",
  "velocity",
  "angles",
  "avelocity",
  "punchangle",
  "classname",
  "model",
  "frame",
  "skin",
  "effects",
  "mins",
  "maxs",
  "size",
  "touch",
  "use",
  "think",
  "blocked",
  "nextthink",
  "groundentity",
  "health",
  "frags",
  "weapon",
  "weaponmodel",
  "weaponframe",
  "currentammo",
  "ammo_shells",
  "ammo_nails",
  "ammo_rockets",
  "ammo_cells",
  "items",
  "takedamage",
  "chain",
  "deadflag",
  "view_ofs",
  "button0",
  "button1",
  "button2",
  "impulse",
  "fixangle",
  "v_angle",
  "idealpitch",
  "netname",
  "enemy",
  "flags",
  "colormap",
  "team",
  "max_health",
  "teleport_time",
  "armortype",
  "armorvalue",
  "waterlevel",
  "watertype",
  "ideal_yaw",
  "yaw_speed",
  "aiment",
  "goalentity",
  "spawnflags",
  "target",
  "targetname",
  "dmg_take",
  "dmg_save",
  "dmg_inflictor",
  "owner",
  "movedir",
  "message",
  "sounds",
  "noise",
  "noise1",
  "noise2",
  "noise3",
] as const;

export const NQ_ENTVARS_LAYOUT = buildProgsLayout(0, ENTVARS_FIELDS, NQ_ENTVARS_NAMES);

export const ENTVARS_OFS = layoutOffsets(NQ_ENTVARS_LAYOUT, NQ_ENTVARS_NAMES);

export const ENTVARS_SIZE_WORDS = NQ_ENTVARS_LAYOUT.words;

export interface EntVars extends EntVarFieldsT {}
export class EntVars extends ProgsVarsT {
  constructor(f: Float32Array, i: Int32Array) {
    super(f, i, NQ_ENTVARS_LAYOUT);
  }
}
installVarAccessors(EntVars.prototype, NQ_ENTVARS_LAYOUT, ENTVARS_FIELDS);
